### ISSUE TITLE
add dev script

### ISSUE THREAD

**Issue by JGJP** [n9nome/spa-skeleton#2]
Maybe it's obvious to people who know webpack, but it's not clear to me what a development workflow looks like with this theme?

**Comment by n9nome** [comment]
Hey JGP, sorry for the slow response. Do you have a working install of the project? You can use `npm run build` to compile the assets after making changes (or set it up to `watch` for changes instead). 

So, for now:
Pull down the theme into the `wp-content/themes` directory, install the required plugins (Wordpress REST API Menus), `npm install` (or `yarn`) to pull in the dependencies and then `npm run build` to compile the various assets.

Once the project is completed, we'd supply a production build and the theme would rely on that.

Sorry if that wasn't very helpful, if you have any specific questions please let me know.

**Comment by JGJP** [comment]
Sorry, I should have been more specific, I was looking for a `webpack-dev-server` script.

I've been learning more about Webpack recently though and am now confident I can put this together myself and maybe submit a PR. Thanks for the reply!

**Comment by n9nome** [comment]
Awesome, sounds good 👍
